crudsimple/urls.py
from django.contrib import admin
from django.urls import path
from simplecrud import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.tampildata),
    path('inputdata/',views.inputdata),
    path('simpandata',views.simpandata),
    path('hapusdata/<int:id>',views.hapusdata),
    path('editdata/<int:id>',views.editdata),
    path('updatedata/<int:id>',views.updatedata),    
    path('lihatdata/<int:id>',views.lihatdata) 
]

simplecrud/models.py
from django.db import models

class Crudsimple(models.Model):
    id = models.IntegerField()
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=50)
    nip = models.IntegerField()
    divisi = models.CharField(max_length=50)
    alamat = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)

    class Meta:
        db_table = "simplecrud"

simplecrud/forms.py
from django import forms

from simplecrud.models import Crudsimple

class CrudsimpleForm(forms.ModelForm):
    class Meta:
        model = Crudsimple
        fields = "__all__"

simplecrud/views.py
from django.shortcuts import render,redirect
from simplecrud.forms import CrudsimpleForm
from simplecrud.models import Crudsimple

def tampildata(request):        
    return render(request,"index.html",{'tampilkandata':Crudsimple.objects.all()})

def inputdata(request):
    return render(request, "inputdata.html")

def simpandata(request):
    if request.method == "POST":
        form = CrudsimpleForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/') #Lihat Pada urls.py saat ingin men-redirect setelah aksi save.
            except:
                pass
    else:
        form = CrudsimpleForm()
    return render(request,'inputdata.html',{'form':form})

def hapusdata(request, id):
    Crudsimple.objects.get(id=id).delete()
    return redirect('/')

def editdata(request, id):
    return render(request, "editdata.html", {'editdatanya':Crudsimple.objects.get(id=id)})

def updatedata(request, id):
    formupdatedata = CrudsimpleForm(request.POST, instance=Crudsimple.objects.get(id=id))
    if formupdatedata.is_valid():
        formupdatedata.save()
        return redirect('/')
    return render(request,'editdata.html',{'updatedatanya':Crudsimple.objecs.get(id=id)})

def lihatdata(request, id):
    return render(request, "detail.html", {'lihatdatanya':Crudsimple.objects.get(id=id)})

simplecrud/templates/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <nav class="navbar navbar-light justify-content-between" style="background-color: #116466;">
    <a href="/" class="btn mb-2" style="background-color:#D1E8E2; color:#2C3531"><i class="fas fa-reply"></i> Kembali</a>
  </nav>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <title>Detail Data Pegawai</title>
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body style="background-color:#d2d3d3">
  <br> </br>

  <div class="container">
      <div class="card shadow-sm mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold">Detail Data Pegawai</h6>
        </div>
        <div class="card-body">
          <p>Nama Pegawai&nbsp; &nbsp;: {{lihatdatanya.nama}}<br>
            NIP Pegawai&nbsp; &nbsp; &nbsp; : {{lihatdatanya.nip}}&nbsp;<br>
            Divisi Pekerjaan : {{lihatdatanya.divisi}}<br>
            Alamat Pegawai : {{lihatdatanya.alamat}}<br>
            Jenis Kelamin&nbsp; &nbsp; : {{lihatdatanya.gender}}
          </p>
        </div>
      </div>
    <footer class="mt-5 mb-3">
      <div class="container my-auto">
        <div class="text-center my-auto">
          <span>Developed by <a href="https://github.com/Bintx" target="_blank" style="color: #2C3531;"><b>Bintang Alamsyah</b><a></span>
        </div>
      </div>
    </footer> 
  </div>

  <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

simplecrud/templates/editdata.html
<!DOCTYPE html>
<html lang="en">

<head>
  <nav class="navbar navbar-light justify-content-between" style="background-color: #116466;">
    <a href="/" class="navbar-brand m-0 font-weight-bold" style="color: #D1E8E2;">Database Pegawai</a>
  </nav>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <title>Perubahan Data Pegawai</title>
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body style="background-color:#d2d3d3">
  <br> </br>

  <div class="container">
    <form method="POST" action="/updatedata/{{ editdatanya.id }}">
      {% csrf_token %}
      <div class="card shadow-sm mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold">Edit Data Pegawai</h6>
        </div>
        <div class="card-body">
          <label>Nama Pegawai</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Nama Pegawai" name="nama"
              id="id_nama" value="{{ editdatanya.nama }}">
          </div>
          <label>NIP Pegawai</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan NIP Pegawai" name="nip"
              id="id_nip" value="{{ editdatanya.nip }}" maxlength="11">
          </div>
          <label>Divisi Pekerjaan</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Divisi Pekerjaan"
              name="divisi" id="id_divisi" value="{{ editdatanya.divisi }}">
          </div>
          <label>Alamat</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Asal Alamat Pegawai"
              name="alamat" id="id_alamat" value="{{ editdatanya.alamat }}">
          </div>
          <label>Jenis Kelamin</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Jenis Kelamin Pegawai"
              name="gender" id="id_gender" value="{{ editdatanya.gender }}">
          </div>
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan Data</button>
          <a href="/" class="btn btn-default">Batal</a>
        </div>
      </div>
    </form>
    <footer class="mt-5 mb-3">
      <div class="container my-auto">
        <div class="text-center my-auto">
          <span>Developed by <a href="https://github.com/Bintx" target="_blank" style="color: #2C3531;"><b>Bintang Alamsyah</b><a></span>
        </div>
      </div>
    </footer> 
  </div>

  <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

simplecrud/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <nav class="navbar navbar-light justify-content-between" style="background-color: #116466;">
    <a class="navbar-brand m-0 font-weight-bold" style="color: #D1E8E2;">Database Pegawai</a>
    <a href="inputdata/" class="btn mb-2" style="background-color:#D1E8E2; color:#2C3531"><i class="fas fa-upload"></i> Tambah Data Pegawai</a>
  </nav>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <title>Data Pegawai</title>
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'datatable/datatables.min.css' %}" rel="stylesheet">

</head>

<body style="background-color:#E3E2DF">
  <br> </br>
  <div class="container">
    <div class="card shadow-sm mb-4" style="width: 100%;">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold">List Daftar Pegawai</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr style="text-align: center;">
                <th style="width: 20px">No.</th>
                <th>Nama Pegawai</th>
                <th style="width: 90px;">Aksi</th>
              </tr>
            </thead>
            <tbody>
              {% for tampilkandatanya in tampilkandata %}
              <tr>
                <td style="text-align: center">{{ forloop.counter }}</td>
                <td>{{ tampilkandatanya.nama }}</td>
                <td style="text-align: center">
                  <a href="/lihatdata/{{ tampilkandatanya.id }}" class="btn btn-warning btn-sm" title="Lihat Data"><i
                      class="fas fa-eye"></i></a>                
                  <a href="/editdata/{{ tampilkandatanya.id }}" class="btn btn-primary btn-sm" title="Ubah Data"><i
                    class="fas fa-edit"></i></a>
                  <a href="/hapusdata/{{ tampilkandatanya.id }}" class="btn btn-danger btn-sm" title="Hapus Data"><i
                      class="fas fa-trash"></i></a>   
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <footer class="mt-5 mb-3">
      <div class="container my-auto">
        <div class="text-center my-auto" id="footer">
          <span>Developed by <a href="https://github.com/Bintx" target="_blank" style="color: #2C3531;"><b>Bintang Alamsyah</b><a></span>
        </div>
      </div>
    </footer> 
  </div>
 <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
 <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'datatable/datatables.min.js' %}"></script> 
 <script>
   $(document).ready(function () {
     $('#dataTable').DataTable();
   });
 </script>

</body>

</html>

simplecrud/templates/inputdata.html
<!DOCTYPE html>
<html lang="en">

<head>
  <nav class="navbar navbar-light justify-content-between" style="background-color: #116466;">
    <a href="/" class="navbar-brand m-0 font-weight-bold" style="color:#D1E8E2;">Database Pegawai</a>
  </nav>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <title>Penambahan Data Pegawai</title>
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">  
</head>

<body style="background-color:#d2d3d3">
  <br> </br>
  <div class="container">
    <form method="POST" action="/simpandata">
      {% csrf_token %}
      <div class="card shadow-sm mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold">Input Data Pegawai</h6>
        </div>
        <div class="card-body">
          <label>Nama Pegawai</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Nama Pegawai" name="nama"
              id="id_nama">
          </div>
          <label>NIP Pegawai</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan NIP Pegawai" name="nip"
              id="id_nip" maxlength="11">
          </div>
          <label>Divisi Pekerjaan</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Divisi Pekerjaan"
              name="divisi" id="id_divisi">
          </div>
          <label>Alamat</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Alamat Pegawai"
              name="alamat" id="id_alamat">
          </div>
          <label>Jenis Kelamin</label>
          <div class="form-group">
            <input type="text" class="form-control form-control-user" placeholder="Masukkan Jenis Kelamin"
              name="gender" id="id_gender">
          </div>
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Simpan Data</button>
          <a href="/" class="btn btn-default">Batal</a>
        </div>
      </div>
    </form>
    <footer class="mt-5 mb-3">
      <div class="container my-auto">
        <div class="text-center my-auto">
          <span>Developed by <a href="https://github.com/Bintx" target="_blank" style="color: #2C3531;"><b>Bintang Alamsyah</b><a></span>
        </div>
      </div>
    </footer> 
  </div>

  <script src="{% static 'jquery/jquery.slim.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>